### ISSUE TITLE
error in certbot

### ISSUE THREAD

**Issue by hmdqr** [nesosuke/mastodon-install-script#32]
I got while installing with a fresh install of Debian 10 with Contabo: 
<q>
usage:certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default, it will attempt to use a webserver both for obtaining and installing the certificate. 
</q>
then i got: 
<q>
certbot: error: argument -d/--domains/--domain: expected one argument
</q>
Any suggestions?
Thank you!

**Comment by nesosuke** [comment]
I found some mistakes in install.sh, and fixed them. 

However, not yet tested on latest version of Mastodon. 
Please tell me another error if happens. 

Thank you.
